Fix unity builds on Mac
SystemMacOS.mm may get included with other C++ files and built a C++, causing
errors like:
```
In file included from /Users/sftnight/build/workspace/lcg_nightly_pipeline/build/frameworks/Gaudi-v40r4/src/Gaudi-v40r4-build/GaudiKernel/CMakeFiles/GaudiKernel.dir/Unity/unity_11_cxx.cxx:19:
In file included from /Users/sftnight/build/workspace/lcg_nightly_pipeline/build/frameworks/Gaudi-v40r4/src/Gaudi/v40r4/GaudiKernel/src/Lib/Platform/SystemMacOS.mm:14:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX26.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSProcessInfo.h:5:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX26.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:6:
/Library/Developer/CommandLineTools/SDKs/MacOSX26.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:616:1: error: expected unqualified-id
  616 | @class NSString, Protocol;
      | ^
/Library/Developer/CommandLineTools/SDKs/MacOSX26.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:618:9: error: unknown type name 'NSString'
  618 | typedef NSString * NSExceptionName NS_TYPED_EXTENSIBLE_ENUM;
      |         ^
```